import './globals.css'
import Nav from './components/Nav'
import { getServerSession } from 'next-auth/next'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import Hydrate from './components/Hydrate'
import { Playfair_Display, Lato } from 'next/font/google'

const playfair = Playfair_Display({weight: ['900','700'], subsets:['latin'], variable: '--font-playfair'})
const lato = Lato({
  subsets:['latin'], 
  display:'swap',
  weight: ['400','700'],
  variable: '--font-lato'
})

export const metadata = {
  title: 'VergePDX Shop',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  console.log(session)
  return (
    <html className={`${lato.variable} ${playfair.variable}`}  >
      <Hydrate>
      
        <Nav user={session?.user} expires={session?.expires as string}/>
        {children}
      </Hydrate>
      </html>
  )
}
