import './globals.css'
import Nav from './components/Nav'
import { getServerSession } from 'next-auth/next'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import Hydrate from './components/Hydrate'

export const metadata = {
  title: 'VergePDX Shop',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  console.log(session)
  return (
    <html>
      <body className="mx-1 md:mx-6">
      <Hydrate>
        <Nav user={session?.user} expires={session?.expires as string}/>
        {children}
</Hydrate>
      </body>
      </html>
  )
}
